plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.cgl.ifind'
version = '1.0.0'

android {
  namespace "expo.modules.stopappassist"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
  buildFeatures {
    aidl true
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'dev.rikka.shizuku:api:13.1.5'
  implementation 'dev.rikka.shizuku:provider:13.1.5'
}
